sudo: required
services:
  - docker

before_install:
  - docker build -t thainam83vn/multi-container-client-test -f ./client/Dockerfile.dev .

script:
  - docker run thainam83vn/multi-container-client-test npm test -- --coverage
