sudo: required
services:
  - docker

before_install:
  - docker build -t thainam83vn/multi-container-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run thainam83vn/multi-container-client-test npm test -- --coverage

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t thainam83vn/multi-container-client ./client
  - docker build -t thainam83vn/multi-container-nginx ./nginx
  - docker build -t thainam83vn/multi-container-server ./server
  - docker build -t thainam83vn/multi-container-worker ./worker
  - docker push thainam83vn/multi-container-client
  - docker push thainam83vn/multi-container-nginx
  - docker push thainam83vn/multi-container-server
  - docker push thainam83vn/multi-container-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-793085127332
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
